### ISSUE TITLE
Houdini Issues (19.0.589 p3)

### ISSUE THREAD

**Issue by EfthymisB** [shotgunsoftware/tk-multi-breakdown2#37]
Hey,

I would also like to flag some issues I have when running the app in Houdini (tested both with v0.2.3 and v0.2.5).

1.  The items have a light gray/white background and the text information is not present (I can only see the titles). I didn't manage to find anything about the background color in `ui_config.py` / `ui_config_advanced.py`.

_I get the following error when I launch the app, which might be related._

`[WARNING tk-framework-shotgunutils] Error retrieving value for stored user setting 'splitter_state' - reverting to to default value. Error details: 'utf-8' codec can't decode byte 0xff in position 3: invalid start byte`

![image](https://user-images.githubusercontent.com/87680516/199215888-fccee4a9-4e40-422f-89c7-92a3cef329bc.png)

2. Browsing the file history is incredibly slow, no matter how many items exist (runs perfectly in Maya, with no lags).
https://user-images.githubusercontent.com/87680516/199220139-592a9d70-3471-468f-b79c-162861df9072.mp4

Linux Centos 7
Houdini 19.0.589 python3

Please let me know if you need more information.

Thanks,
Efthymios

**Comment by staceyoue** [comment]
Hi @EfthymisB, thank you for trying out the app with Houdini!

> The items have a light gray/white background and the text information is not present (I can only see the titles). I didn't manage to find anything about the background color in ui_config.py / ui_config_advanced.py.

The background for file items uses the palettes `midlight` color, and is done so [here](https://github.com/shotgunsoftware/tk-multi-breakdown2/blob/0104b045d6ebbe41d4a754bf9704db41b0984f0d/python/tk_multi_breakdown2/file_model.py#L293-L294). To control this background color value from the `ui_config_advanced.py` hook, we would need modify the `file_model.py` to set up the model role to call the hook method, as done [here](https://github.com/shotgunsoftware/tk-multi-breakdown2/blob/0104b045d6ebbe41d4a754bf9704db41b0984f0d/python/tk_multi_breakdown2/file_model.py#L517-L525) for other model roles. Feel free to make the code change and create a PR, otherwise we can log this as an improvement and will get to it when we can.

There error that you're seeing, I don't believe is related to the color issue.

> Browsing the file history is incredibly slow, no matter how many items exist (runs perfectly in Maya, with no lags)

Even with a couple items it performs this poorly? It looks like the paint method for the file history view may be the issue. On paint, the file history will call some of the `ui_config_advanced.py` methods to get the data to display, you may want to [check these functions ](https://github.com/shotgunsoftware/tk-multi-breakdown2/blob/0104b045d6ebbe41d4a754bf9704db41b0984f0d/python/tk_multi_breakdown2/file_history_model.py#L81-L88)to see if any of them are slow, which would be causing the whole file history view to have poor responsiveness.

**Comment by EfthymisB** [comment]
Hi @staceyoue, 

Thanks for the very detailed and quick reply! I'll try what you suggested and I'll get back to you!

**Comment by EfthymisB** [comment]
Hi again @staceyoue,

I created a new hook method for the `QtCore.Qt.BackgroundRole` and it works perfectly. I'll try to create a PR soon (the `light` palette looks quite nice in Houdini btw). ✔️ 

Regarding the file-history view slowness, I did measure all the relevant `ui_config_advanced` hook methods as well as some of the FileHistoryModel's methods (`data`, `load_data`, `_populate_item`, `_set_tooltip`) and the duration on all of them was negligible (milliseconds). However, these commands run many times even, if I just hover over a file history time (wasn't sure if this is normal or not).

Do you have anything else in mind that could be responsible for the file-history view's poor responsiveness?

**Comment by staceyoue** [comment]
I've logged this performance issue for our QA to look into.

In the meantime, you can try turning off the hover events for the file history view by removing this [line](https://github.com/shotgunsoftware/tk-multi-breakdown2/blob/0104b045d6ebbe41d4a754bf9704db41b0984f0d/python/tk_multi_breakdown2/dialog.py#L308) to see if the hover events are causing the slow down.

**Comment by EfthymisB** [comment]
Looks like that was it! Disabling the mouse tracking improved significantly the responsiveness! Thank you @staceyoue!

**Comment by staceyoue** [comment]
No problem! We will look into improving performance with mouse tracking on (without mouse tracking you will not receive hover event functionality).

**Comment by RicardoMusch** [comment]
@EfthymisB Did you ever get to make a PR for the color issues?
We would love to use this in houdini but the color scheme issues make using breakdown2 quite a pain atm.

**Comment by brettmaker** [comment]
Yeah we are experiencing the same color scheme issue. Can't read the file items. Can we get a PR for it?

**Comment by EfthymisB** [comment]
Hello, 

Sorry for the late reply. I've just created a PR. I've found that the `light` brush is a good option for Maya/Houdini/Nuke but can be changed if needed.

https://github.com/shotgunsoftware/tk-multi-breakdown2/pull/46
